#!/usr/bin/env node
'use strict';
/**
 * Regenerate the Ireland link blocks on the two live Irish hubs from the
 * built Ireland pages, so the hubs can never drift from the cluster.
 *
 *   node scripts/nl/ie-hubs.js [--dry]
 *
 * /coding-classes-in-ireland: cards for the guides (ag- doors) and the cities,
 * then compact link lists for counties and council areas, provinces, areas
 * and towns. /ai-and-machine-learning-classes-in-ireland: cards for the
 * guides and a pointer to the places on the national page. Both .md twins
 * carry the same links. Each block sits between BEGIN and END markers; the
 * first run replaces the sections inserted by hand on 16 September 2026.
 *
 * A module may set hub: { group, tag, blurb }. group is one of guide, city,
 * county, province, area, town; without it the group follows the module
 * (ag- door = guide, city = city, governorate = county, district = area).
 * Order follows the Done table in IRELAND-PROGRESS.md, then anything newer.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const DIR = path.join(ROOT, 'content', 'ie');
const PAGES = path.join(ROOT, 'src', 'pages');
const DRY = process.argv.includes('--dry');

const strip = s => String(s).replace(/<[^>]+>/g, '').replace(/&middot;/g, '·').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
const h = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// ---------------------------------------------------------------- pages
const tracker = fs.readFileSync(path.join(ROOT, 'IRELAND-PROGRESS.md'), 'utf8');
const order = [...tracker.matchAll(/^\| \d+ \| ([a-z0-9-]+) \(/gm)].map(m => m[1]);
const mods = fs.readdirSync(DIR).filter(f => f.endsWith('.js')).map(f => {
  const p = path.join(DIR, f);
  delete require.cache[require.resolve(p)];
  return require(p);
}).filter(m => fs.existsSync(path.join(PAGES, m.slug + '.html')));
const rank = m => { const i = order.indexOf(m.slug); return i === -1 ? 1e6 : i; };
mods.sort((a, b) => rank(a) - rank(b) || a.slug.localeCompare(b.slug));

function groupOf(m) {
  if (m.hub && m.hub.group) return m.hub.group;
  if (m.cluster === 'ag') return 'guide';
  return { city: 'city', governorate: 'county', district: 'area' }[m.pageType] || 'town';
}
const label = m => strip(m.h1);
const blurb = m => (m.hub && m.hub.blurb) || strip(m.twitterDescription);
const tag = m => (m.hub && m.hub.tag) || (groupOf(m) === 'guide' ? 'GUIDE' : strip(m.place ? m.place.name : m.h1).toUpperCase());
const placeName = m => strip(m.place ? m.place.name : m.h1);

const guides = mods.filter(m => groupOf(m) === 'guide');
const cities = mods.filter(m => groupOf(m) === 'city');
const LISTS = [
  ['county', 'Counties and council areas'],
  ['province', 'Provinces'],
  ['area', 'City areas'],
  ['town', 'Towns']
];

// ---------------------------------------------------------------- blocks
function nationalHtml() {
  const card = m => `            <article class="cp-au-city">\n                <span class="tag">${h(tag(m))}</span>\n                <h3><a href="/${m.slug}">${h(label(m))}</a></h3>\n                <p>${h(blurb(m))}</p>\n            </article>\n`;
  const lists = LISTS.map(([g, title]) => {
    const ms = mods.filter(m => groupOf(m) === g);
    if (!ms.length) return '';
    return `            <p class="cp-lede"><strong>${title}:</strong> ${ms.map(m => `<a href="/${m.slug}">${h(placeName(m))}</a>`).join(' &middot; ')}</p>\n`;
  }).join('');
  return '<!-- BEGIN IRELAND PAGES (generated by scripts/nl/ie-hubs.js; edit the content/ie modules, not this block) -->\n' +
    '<section class="cp-section" id="ireland-pages">\n' +
    '    <div class="cp-wrap">\n' +
    '        <div class="cp-shead">\n' +
    '            <span class="cp-eyebrow">Ireland, page by page</span>\n' +
    '            <h2 class="cp-h2">Coding classes near you, and guides to choosing well.</h2>\n' +
    '            <p class="cp-lede">Pages for Irish places and for the questions Irish families ask most, each written for its own readers, with its facts checked at the source.</p>\n' +
    '        </div>\n' +
    '        <div class="cp-au-cities">\n' + guides.concat(cities).map(card).join('') + '        </div>\n' +
    (lists ? '        <div class="cp-shead">\n' + lists + '        </div>\n' : '') +
    '    </div>\n' +
    '</section>\n' +
    '<!-- END IRELAND PAGES -->\n';
}

function nationalMd() {
  const lines = ['<!-- ireland-pages:start -->', '', 'Ireland, page by page', '', '## Coding classes near you, and guides to choosing well.', '',
    'Pages for Irish places and for the questions Irish families ask most, each written for its own readers, with its facts checked at the source.', ''];
  for (const m of guides.concat(cities)) lines.push(`- [${label(m)}](/${m.slug}): ${blurb(m)}`);
  for (const [g, title] of LISTS) {
    const ms = mods.filter(m => groupOf(m) === g);
    if (ms.length) lines.push('', `**${title}:** ` + ms.map(m => `[${placeName(m)}](/${m.slug})`).join(' · '));
  }
  lines.push('', '<!-- ireland-pages:end -->');
  return lines.join('\n');
}

function aiHtml() {
  const items = guides.map(m => `      <div><h3><a class="ag-inline-link" href="/${m.slug}">${h(label(m))}</a></h3><p>${h(blurb(m))}</p></div>\n`).join('');
  return '<!-- BEGIN IRELAND PAGES (generated by scripts/nl/ie-hubs.js; edit the content/ie modules, not this block) -->\n' +
    '<section class="ag-section" id="ireland-pages">\n' +
    '  <div class="ag-wrap">\n' +
    '    <div class="ag-section-head">\n' +
    '      <p class="ag-eyebrow">More for Irish learners</p>\n' +
    '      <h2>Guides for Irish families, and pages for Irish places</h2>\n' +
    '      <p class="ag-lede">Each page answers one question for one audience, with its facts read at the source.</p>\n' +
    '    </div>\n' +
    '    <div class="ag-grid-3">\n' + items + '    </div>\n' +
    `    <p class="ag-mt-40">Pages for Irish places, ${cities.length + mods.filter(m => groupOf(m) !== 'guide' && groupOf(m) !== 'city').length} so far, are listed on <a class="ag-inline-link" href="/coding-classes-in-ireland">the national Ireland page</a>.</p>\n` +
    '  </div>\n' +
    '</section>\n' +
    '<!-- END IRELAND PAGES -->\n';
}

function aiMd() {
  const lines = ['<!-- ireland-pages:start -->', '', 'More for Irish learners', '', '## Guides for Irish families, and pages for Irish places', '',
    'Each page answers one question for one audience, with its facts read at the source.', ''];
  for (const m of guides) lines.push(`- [${label(m)}](/${m.slug}): ${blurb(m)}`);
  lines.push('', 'Pages for Irish places are listed on [the national Ireland page](/coding-classes-in-ireland).', '', '<!-- ireland-pages:end -->');
  return lines.join('\n');
}

// ---------------------------------------------------------------- write
function replaceBlock(file, block, markers, firstRun) {
  const p = path.join(PAGES, file);
  let s = fs.readFileSync(p, 'utf8');
  const eol = s.includes('\r\n') ? '\r\n' : '\n';
  const b = block.replace(/\r?\n/g, eol);
  let start = s.indexOf(markers[0]), end;
  if (start !== -1) {
    end = s.indexOf(markers[1], start);
    if (end === -1) throw new Error(file + ': start marker without end marker');
    end += markers[1].length;
    if (s.slice(end, end + eol.length) === eol) end += eol.length;
  } else {
    start = s.indexOf(firstRun[0]);
    end = firstRun[1] ? s.indexOf(firstRun[1], start + 1) : -1;
    if (start === -1 || end === -1) throw new Error(file + ': Ireland block not found (neither markers nor the first-run anchors)');
    if (firstRun[2]) end += firstRun[1].length;
  }
  const out = s.slice(0, start) + b + s.slice(end);
  if (out === s) return file + ': unchanged';
  if (!DRY) fs.writeFileSync(p, out, 'utf8');
  return file + (DRY ? ': would update' : ': updated');
}

const results = [
  replaceBlock('coding-classes-in-ireland.html', nationalHtml(), ['<!-- BEGIN IRELAND PAGES', '<!-- END IRELAND PAGES -->'],
    ['<!-- ============================== IRELAND, PAGE BY PAGE', '<!-- ============================== STUDENT PROJECTS', false]),
  replaceBlock('coding-classes-in-ireland.md', '\n\n' + nationalMd() + '\n\n', ['\n\n<!-- ireland-pages:start -->', '<!-- ireland-pages:end -->\n\n'],
    ['\n\nIreland, page by page', 'Real shipped student projects', false]),
  replaceBlock('ai-and-machine-learning-classes-in-ireland.html', aiHtml() + '\n', ['<!-- BEGIN IRELAND PAGES', '<!-- END IRELAND PAGES -->'],
    ['<!-- ============================== IRELAND PAGES', '<!-- ============================== START', false]),
  replaceBlock('ai-and-machine-learning-classes-in-ireland.md', nationalMdAiWrap(), ['<!-- ireland-pages:start -->', '<!-- ireland-pages:end -->\n\n'],
    ['More for Irish learners', 'Start here', false])
];
function nationalMdAiWrap() { return aiMd() + '\n\n'; }

console.log(`Ireland hubs: ${guides.length} guides, ${cities.length} cities, ${mods.length - guides.length - cities.length} other places`);
results.forEach(r => console.log('  ' + r));
